spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
server.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonypagad8@gmail.com
spring.mail.password=ulmhaeuydoaoctup
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_SkxYdnBBFy1FFv
razorpay.key.secret=KN7L6ed4tX0hK1SwQoIli0Q8

cloudinary.cloud.name=duyadzw4p
cloudinary.api.key=781855564433973
cloudinary.api.secret=8lkH08o_k_405ZTLc5_x8pY38Rw